import PDFDocument from 'pdfkit';

export function generateConsultationPdfBuffer(consultation: any, patient: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text('Suga.Health', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(16).text('Patient Consultation & Intake', { align: 'center' });
      doc.moveDown(2);

      // Meta info
      doc.fontSize(10).font('Helvetica').text(`Consultation ID: ${consultation.id}`);
      doc.text(`Date Submitted: ${new Date(consultation.submittedAt || consultation.createdAt).toLocaleString()}`);
      doc.text(`Primary Concern: ${consultation.category}`);
      doc.moveDown(1.5);

      // Patient Info
      doc.fontSize(14).font('Helvetica-Bold').text('Patient Information');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica');
      doc.text(`Name: ${patient.firstName} ${patient.lastName}`);
      doc.text(`DOB: ${patient.dateOfBirth}`);
      if (patient.biologicalSex) doc.text(`Biological Sex: ${patient.biologicalSex}`);
      doc.moveDown(1.5);

      // Responses
      doc.fontSize(14).font('Helvetica-Bold').text('Consultation Responses');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica');

      if (consultation.responses) {
        for (const [key, value] of Object.entries(consultation.responses)) {
          doc.font('Helvetica-Bold').text(`${key}:`, { continued: true }).font('Helvetica').text(` ${value}`);
          doc.moveDown(0.5);
        }
      } else {
        doc.text('No specific responses recorded.');
      }
      doc.moveDown(1);

      // Footer
      doc.fontSize(8).fillColor('gray').text('Generated by Suga.Health Secure Clinical System', 50, 780, { align: 'center', lineBreak: false });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export function generatePrescriptionPdfBuffer(prescription: any, consultation: any, patient: any, doctor: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(24).font('Helvetica-Bold').text('Suga.Health', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(16).text('Official Prescription', { align: 'center' });
      doc.moveDown(2);

      // Doctor & Meta
      doc.fontSize(10).font('Helvetica').text(`Prescription ID: ${prescription.id}`);
      doc.text(`Finalized: ${new Date(prescription.finalizedAt).toLocaleString()}`);
      doc.text(`Consultation Reference: ${consultation.category}`);
      doc.moveDown(0.5);
      doc.font('Helvetica-Bold').text(`Prescriber: `, { continued: true }).font('Helvetica').text(`Dr. ${doctor.lastName} (${doctor.uid})`);
      doc.moveDown(1.5);

      // Patient Info
      doc.fontSize(14).font('Helvetica-Bold').text('Patient Information');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica');
      doc.text(`Name: ${patient.firstName} ${patient.lastName}`);
      doc.text(`DOB: ${patient.dateOfBirth}`);
      doc.moveDown(1.5);

      // Medications
      doc.fontSize(14).font('Helvetica-Bold').text('Medications');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);

      if (prescription.medications && Array.isArray(prescription.medications)) {
        prescription.medications.forEach((med: any, i: number) => {
          doc.fontSize(11).font('Helvetica-Bold').text(`${i + 1}. ${med.medicationName} ${med.dosageStrength}`);
          doc.fontSize(10).font('Helvetica');
          if (med.activeIngredient) doc.text(`Active Ingredient: ${med.activeIngredient}`);
          doc.text(`Quantity: ${med.quantity}`);
          doc.text(`Form/Route: ${med.pharmaceuticalForm || 'N/A'} / ${med.route || 'N/A'}`);
          doc.text(`Frequency: ${med.frequency}`);
          doc.text(`Instructions: ${med.timingInstructions || 'None'}`);
          if (med.specialInstructions) doc.text(`Special Instructions: ${med.specialInstructions}`);
          doc.moveDown(1);
        });
      } else {
        doc.fontSize(10).font('Helvetica').text('No medications listed.');
      }

      // Footer
      doc.fontSize(8).fillColor('gray').text('This document is electronically generated and signed.', 50, 780, { align: 'center', lineBreak: false });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
